image: maven:3.6.0-jdk-11

stages:
  - test
  - build
  - docker
  - deploy
  - release

test:
  stage: test
  services:
    - name: cnadiminti/dynamodb-local:latest
      alias: dynamodb
  script:
    - sh gradlew clean check
  variables:
    AMAZON_DYNAMODB_ENDPOINT: "http://dynamodb:8000/"
    AMAZON_DYNAMODB_REGION: ""
  except:
    - master
    - release
    - tags

build-master:
  stage: build
  services:
    - name: cnadiminti/dynamodb-local:latest
      alias: dynamodb
  script:
    - sh gradlew clean check bootJar
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_${CI_JOB_ID}"
    when: always
    expire_in: 7d
    paths:
      - build/libs/sap-mock-backend-*.jar
  variables:
    AMAZON_DYNAMODB_ENDPOINT: "http://dynamodb:8000/"
    AMAZON_DYNAMODB_REGION: ""
  only:
    - master
    - release
    - tags

docker-master:
  stage: docker
  image: docker:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --rm -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

docker-release:
  stage: docker
  image: docker:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --rm -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - release
    - tags
