--liquibase formatted sql
--changeset liquibase:sqlFile-creation

DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
	ID INT(11) AUTO_INCREMENT,
    SAP_USERNAME VARCHAR(45) NOT NULL,
  	EXCHANGE_USERNAME VARCHAR(45) NOT NULL,
    EXCHANGE_DOMAIN VARCHAR(128) NOT NULL,
	TIMEZONE VARCHAR(128) NOT NULL,
  	CREATION_DATE Date NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFICATION_DATE date,
  	FIRST_NAME VARCHAR(45),
  	LAST_NAME VARCHAR(45),
  	REGISTRATION_STATUS tinyint,
  	CONSTRAINT user_pk PRIMARY KEY (ID)
);